name = "Ruins of Aunis"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33dd620ab5ccaed8fb5c24dddbd0054ca660f2ccab7f8974abbb91906abc3e76"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
