name = "Ruins of Aunis"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc4a1fb87de32fc9aadf6a120aa05631e8fdbbcc533f2309f77cc1736d683cb4"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
