name = "Ruins of Aunis"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b91c600faf337de718af7e541c2f2e67afec876f701fffcbd3a77c108a5fe82d"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
