name = "Ruins of Aunis"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cac383a5703d4a6b2ff081d03cd4c4b96bbcdcf6004ce1330aacd0e07e945e82"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
