name = "Ruins of Aunis"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd0cbf4d2bceb3ae399f946247879e5ae5a7b152ac01bb17a915b5a66fec2dc2"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
