name = "Ruins of Aunis"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a3c5a6de300eee5b2c206c48f78b84ada319103e8b4dfa3dbe2d9e858ba8ce7"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
