name = "Ruins of Aunis"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ca45e5fba422eaf98788efe63f9473bebb927ac09cb23eb58d3a37c2643fbba"

[versions]
forge = "14.23.0.2486"
minecraft = "1.12.2"
