name = "AsmodeusCore"
filename = "AsmodeusCore-1.12.2-0.0.25.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3231/302/AsmodeusCore-1.12.2-0.0.25.jar"
hash-format = "murmur2"
hash = "1665756608"

[update]
[update.curseforge]
file-id = 3231302
project-id = 303101
release-channel = "beta"
