name = "BNBGamingLib"
filename = "BNBGamingLib-1.12.2-2.17.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2698/688/BNBGamingLib-1.12.2-2.17.6.jar"
hash-format = "murmur2"
hash = "1245112832"

[update]
[update.curseforge]
file-id = 2698688
project-id = 229587
release-channel = "beta"
