name = "ExtraPlanets"
filename = "ExtraPlanets-1.12.2-0.7.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3213/697/ExtraPlanets-1.12.2-0.7.2.jar"
hash-format = "murmur2"
hash = "374200387"

[update]
[update.curseforge]
file-id = 3213697
project-id = 241291
release-channel = "beta"
