name = "Topography"
filename = "Topography-1.12.2-1.14.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3065/647/Topography-1.12.2-1.14.4.jar"
hash-format = "murmur2"
hash = "1418147964"

[update]
[update.curseforge]
file-id = 3065647
project-id = 297878
release-channel = "beta"
