name = "ZPM-Mod"
filename = "zpmmod-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3025/542/zpmmod-1.2.1.jar"
hash-format = "murmur2"
hash = "307667953"

[update]
[update.curseforge]
file-id = 3025542
project-id = 319865
release-channel = "beta"
